### ISSUE TITLE
ask for advice

### ISSUE THREAD

**Issue by zcdliuwei** [damuopel/Fourier#1]
Hello, I'm very interested in your work. What a wonderful display !!
Personally, Fourier seems to imitate the process of human painting, and all the examples you show can be drawn with one stroke.
I would like to ask if Fourier supports multiple strokes.
Suppose there are two butterflies in the original PNG image, or there are multiple paths in my SVG file,
I want to draw two butterflies with two strokes, because if one stroke is used, there will be a big jump between the two targets，
And even if there is only one target or path, I also want to use multiple strokes in order to simplify and not cause a lot of jumping details,
So in general, my question is how to control Fourier drawing so that it can support user-defined stroke number？
I'm looking forward to your answer，Thank you very much。

**Comment by damuopel** [comment]
Thak you very much for your comment. 

Answering your question, the code I wrote is based on [this video](https://www.youtube.com/watch?v=r6sGWTCMz2k&t=1317sl) and there just one path (function) is approximated. If you have multiple paths in your SVG, what you must done is approximate each of the paths as a separate function defined between 0-1 local values. The tricky part may appear when drawing the full path, so the approximated functions may be organized previously. 

In case, you want to separate a target path, you have two options: 1) manually divide the path with a SVG editor; 2) properly define the integration limits when obtaining the coefficients of the approximated functions.

I hope my comment was useful, let me know if I can help you.

**Comment by zcdliuwei** [comment]
> Thak you very much for your comment.
> 
> Answering your question, the code I wrote is based on [this video](https://www.youtube.com/watch?v=r6sGWTCMz2k&t=1317sl) and there just one path (function) is approximated. If you have multiple paths in your SVG, what you must done is approximate each of the paths as a separate function defined between 0-1 local values. The tricky part may appear when drawing the full path, so the approximated functions may be organized previously.
> 
> In case, you want to separate a target path, you have two options: 1) manually divide the path with a SVG editor; 2) properly define the integration limits when obtaining the coefficients of the approximated functions.
> 
> I hope my comment was useful, let me know if I can help you.

Thank you for your timely and useful reply。
If my SVG has several paths, I will calculate the Fourier series for each path separately, and then draw each path separately on the same canvas. In this way, I can draw all paths, and there is no redundant connection between the paths.

What I want to do is to use Canny edge detection algorithm to simplify the edge of the original PNG or JPG image, and then get the coordinate points of each path, calculate each Fourier series separately, and draw it on the same canvas, as just mentioned

**Comment by zcdliuwei** [comment]
> Thak you very much for your comment.
> 
> Answering your question, the code I wrote is based on [this video](https://www.youtube.com/watch?v=r6sGWTCMz2k&t=1317sl) and there just one path (function) is approximated. If you have multiple paths in your SVG, what you must done is approximate each of the paths as a separate function defined between 0-1 local values. The tricky part may appear when drawing the full path, so the approximated functions may be organized previously.
> 
> In case, you want to separate a target path, you have two options: 1) manually divide the path with a SVG editor; 2) properly define the integration limits when obtaining the coefficients of the approximated functions.
> 
> I hope my comment was useful, let me know if I can help you.

Thank you for your timely and useful reply。
If my SVG has several paths, I will calculate the Fourier series for each path separately, and then draw each path separately on the same canvas. In this way, can I draw all paths, and there is no redundant connection between the paths.

What I want to do is to use Canny edge detection algorithm to simplify the edge of the original PNG or JPG image, and then get the coordinate points of each path, calculate each Fourier series separately, and draw it on the same canvas, as just mentioned

**Comment by damuopel** [comment]
To accomplish a result similar that I have in the repository, you may need a analytical representation of the path and I am not sure if you can get those with the Canny Edge Detection algorithm.  If the discretization of the edge is very fine, maybe you are able to approximate the function properly and obtained suitable coefficients.

Regards,
